package com.wellsfargo.counselor.entity;

import java.sql.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToMany;

@Entity
public class Securities {

    @Id // meaning primary key
    @GeneratedValue // will be auto generated by the db
    private long securityId;

    @ManyToMany
    @JoinColumn(name = "portfilioId", nullable = false) // Foreign key to Portfolio table
    private Portfolio portfolio;

    @Enumerated(EnumType.STRING) // Persist the enum as a string
    @Column(nullable = false)
    private InvestmentCategory investmentCategory;

    @Column(nullable = false)
    private Date purchaseDate;

    @Column(nullable = false)
    private int quantity;

    @ManyToMany
    @JoinColumn(name = "clientId", nullable = false) // Foreign key to Portfolio table
    private Client client;


    protected Securities() {

    }

    // Constructor 
    public Securities(Portfolio portfolio) {
        this.portfolio = portfolio;
    }

    // Getters

    public long getSeecutityId() {
        return securityId;
    }

    public Portfolio getPortfolio() {
        return portfolio;
    }

    public InvestmentCategory getInvestmentCategory() {
        return investmentCategory;
    }

    public Date getPurchaseDate() {
        return purchaseDate;
    }

    public int getQuantity() {
        return quantity;
    }

    // Setters 

    public void setPortfolio(Portfolio portfolio) {
        this.portfolio = portfolio;
    }
    
    public void setInvestmentCategory(InvestmentCategory investmentCategory) {
        this.investmentCategory = investmentCategory;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }   

}
